### ISSUE TITLE
two typos in actions.js

### ISSUE THREAD

**Issue by mgylling** [IMSGlobal/caliper-js#201]
Two of the actions in actions.js are misspelled, and the misspelling carries through to the emitted events, which means that unknown actions are generated.  

Is: 
* EnableCloseCaptioning
* DisableCloseCaptioning

Should be:
* EnableClosedCaptioning
* DisableClosedCaptioning

**Comment by arwhyte** [comment]
The correct terms are:

EnabledClosedCaptioning
DisabledClosedCaptioning

Resolved by #202.
