### ISSUE TITLE
What happened to Caliper-js-public

### ISSUE THREAD

**Issue by scody** [IMSGlobal/caliper-js#230]
Hey guys I'm now getting an error when trying to build... Caliper-js-public... does it still exist?

[ERROR] npm ERR! git fetch -a origin (https://github.com/IMSGlobal/caliper-js-public.git) fatal: Authentication failed for 'https://github.com/IMSGlobal/caliper-js-public.git/'

**Comment by arwhyte** [comment]
I believe caliper-js-public was deleted yesterday.  Note that we changed the visibility of caliper-js (formerly private) to public and archived caliper-js-public (redundant) in May 2018. caliper-js-public has been a zombie repo ever since.

Fork/clone caliper-js.  It's the canonical repo.

**Comment by ViktorHaag** [comment]
Recommend to close this issue as answered.

**Comment by bracken** [comment]
Thanks for the issue @scody. I didn't think to search for people linking to it in their package.json files and it looks like there are 6 other people who linked directly to the github repo as well. 
I'll go notify them. 

As a note, that means they were already tied to a deprecated repo that would get no updates. So this is unfortunate, but we needed to help them get switched anyway.

**Comment by scody** [comment]
Fair enough, thanks Viktor and Bracken.

**Comment by bracken** [comment]
I've created issues on all the repos I found through github search that had it in their package.json or yarn files.
